name: Code checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache
        with:
          path: "**/node_modules"
          key: npm-v1-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-v1-

      - name: Install dependencies
        run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Lint contracts
        run: npm run lint-contracts

      - name: Lint scripts
        run: npm run lint-ts

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache
        with:
          path: "**/node_modules"
          key: npm-v1-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-v1-

      - name: Install dependencies
        run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Run tests
        run: npm test
